import { Hospital, Emergency } from "./types";

export const INITIAL_HOSPITALS: Hospital[] = [
  {
    id: "hosp-lagos-1",
    name: "Lagos Island Maternity Hospital",
    address: "Campbell Street, Lagos Island",
    state: "Lagos",
    phoneContact: "+234 1 234 5678",
    locationLat: 6.4497,
    locationLng: 3.4004,
    hasAmbulance: true,
    availableAmbulances: 2,
    totalAmbulances: 3,
    availableBeds: 14,
    totalBeds: 30,
    isVerified: true,
    onboardingStatus: "verified",
    rating: 4.8
  },
  {
    id: "hosp-lagos-2",
    name: "Gbagada General Hospital",
    address: "Hospital Road, Gbagada, Lagos",
    state: "Lagos",
    phoneContact: "+234 803 111 2222",
    locationLat: 6.5492,
    locationLng: 3.3857,
    hasAmbulance: true,
    availableAmbulances: 1,
    totalAmbulances: 2,
    availableBeds: 8,
    totalBeds: 25,
    isVerified: true,
    onboardingStatus: "verified",
    rating: 4.2
  },
  {
    id: "hosp-abuja-1",
    name: "Garki General Hospital",
    address: "Area 8, Garki, Abuja",
    state: "Abuja",
    phoneContact: "+234 9 876 5432",
    locationLat: 9.0353,
    locationLng: 7.4878,
    hasAmbulance: true,
    availableAmbulances: 3,
    totalAmbulances: 4,
    availableBeds: 19,
    totalBeds: 40,
    isVerified: true,
    onboardingStatus: "verified",
    rating: 4.6
  },
  {
    id: "hosp-abuja-2",
    name: "Wuse District Hospital",
    address: "Conakry Street, Wuse Zone 3, Abuja",
    state: "Abuja",
    phoneContact: "+234 805 222 3333",
    locationLat: 9.0664,
    locationLng: 7.4646,
    hasAmbulance: true,
    availableAmbulances: 0,
    totalAmbulances: 2,
    availableBeds: 5,
    totalBeds: 20,
    isVerified: true,
    onboardingStatus: "verified",
    rating: 4.1
  },
  {
    id: "hosp-oyo-1",
    name: "Adeoyo Maternity Teaching Hospital",
    address: "Adeoyo Road, Yemetu, Ibadan",
    state: "Oyo",
    phoneContact: "+234 812 345 6789",
    locationLat: 7.3916,
    locationLng: 3.9054,
    hasAmbulance: true,
    availableAmbulances: 1,
    totalAmbulances: 2,
    availableBeds: 12,
    totalBeds: 35,
    isVerified: true,
    onboardingStatus: "verified",
    rating: 4.5
  },
  {
    id: "hosp-enugu-1",
    name: "ESUT Teaching Hospital (Parklane)",
    address: "Justice Wilkins Street, G.R.A, Enugu",
    state: "Enugu",
    phoneContact: "+234 804 999 0000",
    locationLat: 6.4421,
    locationLng: 7.5098,
    hasAmbulance: true,
    availableAmbulances: 1,
    totalAmbulances: 2,
    availableBeds: 9,
    totalBeds: 22,
    isVerified: true,
    onboardingStatus: "verified",
    rating: 4.4
  },
  {
    id: "hosp-kano-1",
    name: "Murtala Muhammad Specialist Hospital",
    address: "Kofar Mata Road, Kano",
    state: "Kano",
    phoneContact: "+234 809 888 7777",
    locationLat: 11.9962,
    locationLng: 8.5222,
    hasAmbulance: false,
    availableAmbulances: 0,
    totalAmbulances: 0,
    availableBeds: 22,
    totalBeds: 50,
    isVerified: true,
    onboardingStatus: "verified",
    rating: 4.3
  }
];

export const INITIAL_EMERGENCIES: Emergency[] = [
  {
    id: "em-1",
    patientName: "Chinyere Adebayo",
    phoneNumber: "+234 802 345 6789",
    status: "dispatched",
    emergencyType: "maternal",
    severityLevel: 5,
    locationLat: 6.4520,
    locationLng: 3.3980,
    address: "14 Broad Street, Lagos Island, Lagos",
    details: "Staged 38 weeks. Patient reporting severe premature labor contractions and heavy bleeding.",
    hospitalId: "hosp-lagos-1",
    hospitalName: "Lagos Island Maternity Hospital",
    etaMinutes: 8,
    ambulancePlate: "LA-22A-M01",
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString() // 15 mins ago
  },
  {
    id: "em-2",
    patientName: "Aminat Yusuf",
    phoneNumber: "+234 815 678 1234",
    status: "pending",
    emergencyType: "maternal",
    severityLevel: 4,
    locationLat: 9.0380,
    locationLng: 7.4850,
    address: "Area 11, Gasa District, Garki, Abuja",
    details: "Eclampsia symptoms: high fever, intense headaches, and blurred vision at 34 weeks.",
    createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString() // 5 mins ago
  },
  {
    id: "em-3",
    patientName: "Ngozi Okafor",
    phoneNumber: "+234 703 111 0000",
    status: "completed",
    emergencyType: "critical_neonatal",
    severityLevel: 5,
    locationLat: 6.4380,
    locationLng: 7.5020,
    address: "Independence Layout, Enugu",
    details: "Newborn experiencing acute respiratory distress immediately post birth at home.",
    hospitalId: "hosp-enugu-1",
    hospitalName: "ESUT Teaching Hospital (Parklane)",
    ambulancePlate: "EN-758-AB",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString() // 2 hours ago
  },
  {
    id: "em-4",
    patientName: "Fatima Bello",
    phoneNumber: "+234 901 222 3333",
    status: "accepted",
    emergencyType: "maternal",
    severityLevel: 3,
    locationLat: 11.9920,
    locationLng: 8.5180,
    address: "Sabon Gari, Fagge, Kano",
    details: "Patient water broke 18 hours ago, sluggish progress, pre-eclampsia history.",
    hospitalId: "hosp-kano-1",
    hospitalName: "Murtala Muhammad Specialist Hospital",
    createdAt: new Date(Date.now() - 40 * 60 * 1000).toISOString() // 40 mins ago
  }
];

export const CORRESPONDING_LANGUAGES = {
  English: {
    welcome: "Welcome to MamaRoute AI Safety Portal",
    tagline: "Connecting mothers to emergency obstetric care faster.",
    sos: "EMERGENCY SOS",
    tapSos: "Tap if you or a pregnant relative is in danger",
    aiAssistant: "MamaRoute AI Assistant",
    aiPrompt: "How can I help you today? E.g., 'What are danger signs in 3rd trimester?'",
    safetyFirst: "Safety First: In a medical emergency, always trigger the SOS button or visit a hospital. I provide educational maternal guidance but do not replace doctors.",
    emergencyBtn: "I have an emergency! Take me to hospital",
    sosTriggered: "SOS Active: Broadcasting location to emergency teams.",
    seekingHelp: "Locating hospital..."
  },
  Pidgin: {
    welcome: "Welcome to MamaRoute AI Safety Center",
    tagline: "De connect pregnant mama to fast emergency doctor care.",
    sos: "EMERGENCY SOS",
    tapSos: "Press here if you or pregnant person get big wahala",
    aiAssistant: "MamaRoute AI Assistant",
    aiPrompt: "Wetin dey worry you today? E.g., 'Wetin be sign say baby wan come?'",
    safetyFirst: "Observe Safety: If emergency dey, press SOS run go hospital sharp-sharp. I dey give advice but I no be real doctor.",
    emergencyBtn: "Wahala dey! Standard emergency transport",
    sosTriggered: "SOS dey run: We dey send your location to hospital.",
    seekingHelp: "We dey find nearest hospital..."
  },
  Yoruba: {
    welcome: "Kaabo si Gbangba Abo MamaRoute AI",
    tagline: "Siso awon aboyun mo itoju pajawiri ni kiakia.",
    sos: "PAJAWIRI SOS",
    tapSos: "Tẹ ti iwọ tabi aboyun ba wa ninu ewu",
    aiAssistant: "Oluranlowo MamaRoute AI",
    aiPrompt: "Bawo ni mo se le ran e lowo loni? Bi apeere, 'Kini awon ami ewu ninu oyun?'",
    safetyFirst: "Aabo lo se pataki julo: Ti pajawiri ba wa, tẹ bọtini SOS tabi lọ si ile-iwosan immediately. Imọran nikan ni mo n sọ.",
    emergencyBtn: "Pajawiri wa! Gbe mi lo si ile iwosan",
    sosTriggered: "Pajawiri SOS Ti Bẹrẹ: A n fi ibi ti o wa ranse si ile iwosan pajawiri.",
    seekingHelp: "A n wa ile isegun ti o sunmọ..."
  },
  Hausa: {
    welcome: "Barka da zuwa MamaRoute AI Safety Portal",
    tagline: "Haɗa mata masu juna biyu da kulawar gaggawa cikin sauri.",
    sos: "SOS NA GAGGAWA",
    tapSos: "Danna idan kai ko mace mai juna biyu suna cikin haɗari",
    aiAssistant: "MamaRoute AI Assistant",
    aiPrompt: "Yaya zan iya taimaka muku yau? Kamar, 'Mene ne alamun haɗari a cikin juna biyu?'",
    safetyFirst: "Hatsarin farko: Idan akwai matsananciyar gaggawa, danna SOS ko je asibiti kusa. Ina ba da shawarwari ne kawai.",
    emergencyBtn: "Ina da matsala! Kai ni asibiti gobe",
    sosTriggered: "SOS Yana Aiki: Muna aika wurin da kuke zuwa asibitocin gaggawa.",
    seekingHelp: "Neman asibiti mafi kusa..."
  }
};
